//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<System.DateTime> DateOfService { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Services_ Services_ { get; set; }
    }
}
